"""add insight_findings table

Revision ID: 4aeb474f62b8
Revises: 4afc0b79dd15
Create Date: 2026-07-09 17:27:06.269226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aeb474f62b8'
down_revision: Union[str, Sequence[str], None] = '4afc0b79dd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('subject_story_id', sa.UUID(), nullable=True),
    sa.Column('dimension_a', sa.String(), nullable=True),
    sa.Column('dimension_b', sa.String(), nullable=True),
    sa.Column('finding_text', sa.Text(), nullable=False),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("finding_type in ('correlation','most_representative','most_unique','most_complex','theme_bridge','theme_migration')", name='ck_insight_findings_finding_type'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: alembic autogenerate always flags the embeddings ivfflat indexes
    # as "removed" here because they're raw SQL (not SQLAlchemy Index
    # objects) — not a real schema change, so those lines are stripped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insight_findings')
    # ### end Alembic commands ###
