"""add story_fingerprints table

Revision ID: 4afc0b79dd15
Revises: 137b1c28ff9d
Create Date: 2026-07-09 15:06:40.707762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afc0b79dd15'
down_revision: Union[str, Sequence[str], None] = '137b1c28ff9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('version', sa.String(), server_default='v1', nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('summary_source', sa.String(), server_default='rule_based', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("summary_source in ('rule_based','llm')", name='ck_story_fingerprints_summary_source'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'model', 'version', name='uq_story_fingerprints_story_model_version')
    )
    # Note: the ix_embeddings_vector_*_cosine indexes are raw SQL (see the
    # initial migration), so autogenerate always flags them as "removed"
    # here — a false positive, left out on purpose.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('story_fingerprints')
